# This file is where you keep secret settings, passwords, and tokens!
# If you put them in the code you risk committing that info or sharing it

secrets = {
    'ssid' : '', # Wi-Fi Network Name
    'password' : '', # Wi-Fi Password
    "timezone" : "America/New_York",
    'x-api-key': '', # The API key generated by the serverless application
    'endpoint': '', # The API endpoint generated by the serverless application
    'interval': 5
}
